# taken from https://github.com/zaproxy/action-full-scan
name:  Dynamic Scan Using ZAP
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://testasp.vulnweb.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
